version: "{build}"
image: Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
    - JAVA_HOME: C:/Program Files/Java/jdk1.8.0

before_build:
  - java -version
  - mvnw.cmd clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

build_script:
  - mvnw.cmd clean install -Dsurefire.rerunFailingTestsCount=1

on_failure:
  - ps: |
      7z a -r surefire-reports.zip '**\target\surefire-reports\*'
      Push-AppveyorArtifact surefire-reports.zip -DeploymentName 'Surefire Reports'

cache:
  - C:/Users/appveyor/.m2
